language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
  - PROJECT_NAME=metator
  - GITHUB_REPO_NAME=koszullab/metator
os:
- linux
install:
- pip install -r requirements.txt
- pip install pytest pylint pytest-cov pytest-pylint codecov setuptools wheel twine
- python setup.py install
script:
- |
  if [[ $TRAVIS_TAG ]]; then
    python setup.py sdist;
    python setup.py bdist_wheel;
  fi
tags: true