name: Test and Doc

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash -l {0}

permissions:
  contents: write


jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [ "3.9", "3.10", "3.11" ]
        include:
          - os: ubuntu-latest
          # - os: windows-latest
          # - os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
    
      - uses: actions/checkout@v4

      - name: ⚙️ Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 🛠️ Install system dependencies
        run: |
          sudo apt-get update && 
          sudo apt-get install -y default-jre default-jdk &&
          sudo apt-get install -y bowtie2 bwa hmmer prodigal

      - name: 📦 Install package
        run: |
          pip install .[test]

      - name: 🧪 Run tests on ${{ matrix.os }}
        run: |
          ruff check . --select=E9,F63,F7,F82
          pytest --cov --cov-report=xml
