# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    
    - uses: actions/checkout@v3

    - name: Load apt packages
      run: |
        sudo apt-get update
        sudo apt-get -y install git make g++ default-jre default-jdk zlib1g-dev

    - name: Install Louvain
      run: |
        cd external 
        tar -xzf louvain-generic.tar.gz
        cd gen-louvain
        make
        cd ../..
    
    - name: Install Leiden
      run: |
        git clone https://github.com/vtraag/networkanalysis.git
        cd networkanalysis
        ./gradlew build
        cd ..

    - name: Install Conda environment from metator.yaml
      uses: mamba-org/setup-micromamba@v1
      with:
          environment-file: metator.yaml
          generate-run-shell: true
          create-args: >-
            python=${{ matrix.python-version }}

    - name: Test with pytest
      run: |
        micromamba activate metator
        export LOUVAIN_PATH=external/gen-louvain
        export LEIDEN_PATH=networkanalysis/build/libs/networkanalysis-1.2.0.jar
        pytest --pylint --pylint-error-types=EF --pylint-rcfile=.pylintrc --doctest-modules metator
        pytest --cov=metator
        codecov
