# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    
    - uses: actions/checkout@v2

    - name: Load apt packages
      run: |
        sudo apt-get update
        sudo apt-get -y install git make g++ bowtie2 samtools hmmer prodigal
    
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install bwa
      run: |
        git clone https://github.com/lh3/bwa.git
        cd bwa
        make
        cd ..

    - name: Install Louvain
      run: |
        cd external 
        tar -xzf louvain-generic.tar.gz
        cd gen-louvain
        make
        cd ../..
    
    - name: Install Leiden
      run: |
        git clone https://github.com/vtraag/networkanalysis.git
        cd networkanalysis
        ./gradlew build
        cd ../

    - name: Install pytest and dependencies
      run: |
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True
        pip install pytest pylint pytest-cov pylint pytest-pylint codecov
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        export LOUVAIN_PATH=external/gen-louvain
        export LEIDEN_PATH=networkanalysis/build/libs/networkanalysis-1.2.0.jar
        export PATH="$PATH:bwa/"
        pytest --pylint --pylint-error-types=EF --pylint-rcfile=.pylintrc --doctest-modules metator tests
        pytest --cov=metator
        codecov
